# Generated by Django 2.1.7 on 2019-03-14 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190314_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 6, 34, 9, 50376), null=True),
        ),
    ]
