# Generated by Django 2.1.7 on 2019-03-14 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190314_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 14, 6, 38, 25, 825898, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 14, 6, 38, 25, 826024), null=True),
        ),
    ]
